-- Seed: The Deshi Shop products with local fast-loading matching product artwork
DELETE FROM products;

INSERT INTO `products` (`name`, `description`, `price`, `category`, `image_url`, `created_by`) VALUES
('Samsung Galaxy S24 Ultra', 'AI-powered flagship with 200MP camera, S Pen, titanium frame. 6.8\" Dynamic AMOLED display, 5000mAh battery, Snapdragon 8 Gen 3.', 129999.00, 'Smartphones', 'assets/img/products/samsung-galaxy-s24-ultra.svg', 1),
('iPhone 15 Pro Max', 'Titanium design, A17 Pro chip, 48MP camera system with 5x optical zoom. USB-C, Action Button, Always-On display.', 189999.00, 'Smartphones', 'assets/img/products/iphone-15-pro-max.svg', 1),
('Xiaomi 14 Ultra', 'Leica Summilux quad-camera, Snapdragon 8 Gen 3, 5000mAh with 90W fast charging. 6.73\" LTPO AMOLED.', 119999.00, 'Smartphones', 'assets/img/products/xiaomi-14-ultra.svg', 1),
('Realme GT 5 Pro', 'Flagship killer with Snapdragon 8 Gen 3, 50MP Sony IMX890 camera, 5400mAh battery, 100W SuperVOOC.', 45999.00, 'Smartphones', 'assets/img/products/realme-gt-5-pro.svg', 1),
('OnePlus 12', 'Hasselblad camera, Snapdragon 8 Gen 3, 5400mAh with 100W SUPERVOOC. 2K LTPO display, 16GB RAM.', 69999.00, 'Smartphones', 'assets/img/products/oneplus-12.svg', 1),
('MacBook Air M3', 'Ultra-thin with Apple M3 chip, 18-hour battery, Liquid Retina display. 8GB unified memory, 256GB SSD.', 135000.00, 'Laptops', 'assets/img/products/macbook-air-m3.svg', 1),
('ASUS ROG Strix G16', 'Gaming beast: Intel i9-13980HX, RTX 4070, 16\" 240Hz display, 32GB DDR5, advanced cooling system.', 185000.00, 'Laptops', 'assets/img/products/asus-rog-strix-g16.svg', 1),
('HP Pavilion 15', 'Everyday laptop with Intel Core i5-1335U, 8GB RAM, 512GB SSD, 15.6\" FHD IPS display. Backlit keyboard.', 52000.00, 'Laptops', 'assets/img/products/hp-pavilion-15.svg', 1),
('Lenovo IdeaPad Slim 3', 'Budget-friendly with AMD Ryzen 5 7530U, 8GB RAM, 512GB SSD, 15.6\" FHD anti-glare display.', 38500.00, 'Laptops', 'assets/img/products/lenovo-ideapad-slim-3.svg', 1),
('Sony WH-1000XM5', 'Industry-leading ANC wireless headphones, 30-hour battery, premium sound. Multi-point connection, speak-to-chat.', 28999.00, 'Audio', 'assets/img/products/sony-wh-1000xm5.svg', 1),
('JBL Tune 230NC TWS', 'Active noise cancelling TWS earbuds, 40-hour battery, IPX4 water resistance. Smart Ambient Sound.', 4500.00, 'Audio', 'assets/img/products/jbl-tune-230nc-tws.svg', 1),
('Marshall Stanmore III', 'Iconic Bluetooth speaker with Marshall heritage sound. 80W output, multi-directional sound, classic design.', 32000.00, 'Audio', 'assets/img/products/marshall-stanmore-iii.svg', 1),
('AirPods Pro 2nd Gen', 'Apple H2 chip, Adaptive ANC, Personalized Spatial Audio, USB-C charging. Up to 6 hours listening time.', 26999.00, 'Audio', 'assets/img/products/airpods-pro-2nd-gen.svg', 1),
('boAt Rockerz 450', 'Budget wireless headphone with 40mm driver, 15-hour battery, padded ear cushions, dual connectivity.', 1499.00, 'Audio', 'assets/img/products/boat-rockerz-450.svg', 1),
('Apple Watch Ultra 2', 'Rugged smartwatch with advanced fitness tracking, GPS, titanium case. 3000 nit display, 36-hour battery.', 79900.00, 'Wearables', 'assets/img/products/apple-watch-ultra-2.svg', 1),
('Xiaomi Smart Band 8', 'Slim fitness tracker with AMOLED display, 150+ workout modes, 16-day battery. Heart rate, SpO2 monitoring.', 2999.00, 'Wearables', 'assets/img/products/xiaomi-smart-band-8.svg', 1),
('Samsung Galaxy Watch 6', 'Premium smartwatch with BioActive sensor, Wear OS, sleep coaching. Always-On sAMOLED display.', 25999.00, 'Wearables', 'assets/img/products/samsung-galaxy-watch-6.svg', 1),
('Quantum Wireless Mouse', 'Ergonomic wireless mouse, 16000 DPI sensor, silent clicks, 80-hour battery. 2.4GHz USB receiver included.', 1250.00, 'Accessories', 'assets/img/products/quantum-wireless-mouse.svg', 1),
('Baseus 65W GaN Charger', 'Compact 65W GaN fast charger, 3 ports (2 USB-C + 1 USB-A). Charges laptop, phone, earbuds simultaneously.', 2200.00, 'Accessories', 'assets/img/products/baseus-65w-gan-charger.svg', 1),
('Anker PowerCore 20000', '20000mAh portable charger with 65W output, USB-C PD. Charges MacBook, iPhone, iPad simultaneously.', 6500.00, 'Accessories', 'assets/img/products/anker-powercore-20000.svg', 1),
('Samsung T7 Shield SSD', 'Rugged portable SSD, 1TB, USB 3.2 Gen 2, up to 1050MB/s read. IP65 rated, drop resistant.', 9500.00, 'Accessories', 'assets/img/products/samsung-t7-shield-ssd.svg', 1),
('Aura Mechanical Keyboard', 'Compact 75% mechanical keyboard, hot-swappable switches, RGB backlighting, premium PBT keycaps.', 4500.00, 'Gaming', 'assets/img/products/aura-mechanical-keyboard.svg', 1),
('Razer DeathAdder V3', 'Ultra-lightweight ergonomic gaming mouse, 30K DPI optical sensor, 63g weight for competitive gaming.', 5800.00, 'Gaming', 'assets/img/products/razer-deathadder-v3.svg', 1),
('PS5 DualSense Controller', 'Immersive gaming with haptic feedback, adaptive triggers, built-in mic, dual speaker system. Midnight Black.', 6500.00, 'Gaming', 'assets/img/products/ps5-dualsense-controller.svg', 1),
('HyperX Cloud III', 'Comfortable gaming headset with 53mm drivers, DTS spatial audio, memory foam ear cushions, detachable mic.', 8500.00, 'Gaming', 'assets/img/products/hyperx-cloud-iii.svg', 1),
('Canon EOS R50 Camera', 'Compact mirrorless with 24.2MP APS-C sensor, 4K video, intelligent autofocus for creators. Lightweight body.', 78000.00, 'Cameras', 'assets/img/products/canon-eos-r50-camera.svg', 1),
('Sony ZV-E10 II', 'Vlogging camera with 26MP APS-C sensor, 4K 60p video, side-opening vari-angle LCD, directional mic.', 95000.00, 'Cameras', 'assets/img/products/sony-zv-e10-ii.svg', 1),
('GoPro Hero 12 Black', 'Action camera with 5.3K60 video, HyperSmooth 6.0, HDR, 27MP photos. Waterproof to 33ft.', 42000.00, 'Cameras', 'assets/img/products/gopro-hero-12-black.svg', 1),
('DJI Mini 4 Pro Drone', 'Lightweight 4K camera drone, omnidirectional obstacle sensing, 34-minute flight time, ActiveTrack 360.', 62500.00, 'Drones', 'assets/img/products/dji-mini-4-pro-drone.svg', 1),
('DJI Air 3', 'Dual-camera drone with 48MP wide + 48MP mid-tele, 4K/100fps video, 46-minute flight, O4 HD video.', 105000.00, 'Drones', 'assets/img/products/dji-air-3.svg', 1);
